---
# proxmox_create_lxc: creation of a complete LXC container uin porxmox cluster
# tasks file for ansible-role-proxmox-create-lxc/

# Extraer el hostname del inventory_hostname (debe ser el fqdn)
- name: Extract hostname from inventory_hostname (must be fqdn)
  set_fact:
    proxmox_hostname: "{{ inventory_hostname.split('.')[0] }}"

- debug:
    msg: "{{ proxmox_hostname }} - {{inventory_hostname}}"
    verbosity: 2

# Verificar si python-pip está instalado en el nodo proxmox
- name: Verify that python-pip is installed in the Proxmox node
  apt:
    name: python-pip
    state: present
  delegate_to: "{{ api_host }}"

#  Verificar si el módulo proxmoxer de python está instalado
- name: Verify if proxmoxer pip module is installed
  pip:
    name: proxmoxer
    state: present
  delegate_to: "{{ api_host }}"

# Descargar la plantilla del contenedor
- name: Download the container template
  get_url:
    url: "{{ url_ostemplate }}"
    dest: /var/lib/vz/template/cache/
  delegate_to: "{{ api_host }}"
  register: descarga_ostemplate
  tags:
    - descarga
    - download

- debug:
    var: descarga_ostemplate
    verbosity: 2
  tags:
    - descarga
    - download

# Agregar template lxc del container al nodo
- name: Add LXC container template to node
  proxmox_template:
      node: "{{ node }}"
      api_user: "{{ api_user }}"
      api_host: "{{ api_host }}"
      api_password: "{{node_deploy_password}}"
      src: "{{ descarga_ostemplate.dest }}"
      content_type: vztmpl
      state: present
  delegate_to: "{{ api_host }}"
  tags:
      - descarga
      - download

- block:
# see at the end of the block the module_defaults
# eventual additional mounts are defined as a "mounts" list of structures defininfg

    #  Instalar contenedores proxmox en el nodo proxmox idóneo, sin disco adicional
    - name: Install the container with no additional mount
      proxmox:
      delegate_to: "{{ api_host }}"
      when:  (mounts is not defined) or ( mounts|length == 0 )
      register: container0

    - set_fact:
       container: "{{ container0 }}"

    # Instalar contenedores proxmox en el nodo proxmox idóneo, con un disco adicional
    - name: Install the container with one additional mount
      proxmox:
        mounts:
          mp0: "{{ mounts.0.storage|default('local') }}:{{ mounts.0.size|default(30) }},mp={{ mounts.0.mount_point|default('/mnt') }},{% if mounts.0.acl is defined %}acl={{ mounts.0.acl }}{% endif %},{% if mounts.0.quota is defined %}quota={{ mounts.0.quota }}{% endif %}"
      delegate_to: "{{ api_host }}"
      when: ( mounts is defined ) and ( mounts|length == 1 )
      register: container1

    - set_fact:
       container: "{{ container1 }}"
      when: container1.changed

    # Instalar contenedores proxmox en el nodo proxmox idóneo, con dos discos adicionales
    - name: Install the container with two additional mount
      proxmox:
        mounts:
          mp0: "{{ mounts.0.storage|default('local') }}:{{ mounts.0.size|default(30) }},mp={{ mounts.0.mount_point|default('/mnt/0') }},{% if mounts.0.acl is defined %}acl={{ mounts.0.acl }}{% endif %},{% if mounts.0.quota is defined %}quota={{ mounts.0.quota }}{% endif %}"
          mp1: "{{ mounts.1.storage|default('local') }}:{{ mounts.1.size|default(30) }},mp={{ mounts.1.mount_point|default('/mnt/1') }},{% if mounts.1.acl is defined %}acl={{ mounts.1.acl }}{% endif %},{% if mounts.1.quota is defined %}quota={{ mounts.1.quota }}{% endif %}"
      delegate_to: "{{ api_host }}"
      when: ( mounts is defined ) and ( mounts|length == 2 )
      register: container2

    - set_fact:
       container: "{{ container2 }}"
      when: container2.changed

    # Instalar contenedores proxmox en el nodo proxmox idóneo, con tres discos adicionales
    - name: Install the container with three additional mount
      proxmox:
        mounts:
          mp0: "{{ mounts.0.storage|default('local') }}:{{ mounts.0.size|default(30) }},mp={{ mounts.0.mount_point|default('/mnt/0') }},{% if mounts.0.acl is defined %}acl={{ mounts.0.acl }}{% endif %},{% if mounts.0.quota is defined %}quota={{ mounts.0.quota }}{% endif %}"
          mp1: "{{ mounts.1.storage|default('local') }}:{{ mounts.1.size|default(30) }},mp={{ mounts.1.mount_point|default('/mnt/1') }},{% if mounts.1.acl is defined %}acl={{ mounts.1.acl }}{% endif %},{% if mounts.1.quota is defined %}quota={{ mounts.1.quota }}{% endif %}"
          mp2: "{{ mounts.2.storage|default('local') }}:{{ mounts.2.size|default(30) }},mp={{ mounts.2.mount_point|default('/mnt/2') }},{% if mounts.2.acl is defined %}acl={{ mounts.2.acl }}{% endif %},{% if mounts.2.quota is defined %}quota={{ mounts.2.quota }}{% endif %}"
      delegate_to: "{{ api_host }}"
      when: ( mounts is defined ) and ( mounts|length == 3 )
      register: container3

    - set_fact:
       container: "{{ container3 }}"
      when: container3.changed

  module_defaults:
    proxmox:
        node: "{{ node }}"
        api_user: "{{ api_user }}"
        api_host: "{{ api_host }}"
        api_password: "{{ node_deploy_password }}"
        cores: "{{ cores }}"
        memory: "{{ memory }}"
        storage: "{{ storage }}"
        disk: "{{ disk }}"
        hostname: "{{ proxmox_hostname }}"
        netif:
            net0: "name={{ netif_name }},bridge={{ netif_bridge }},{% if (netif_hwaddr is defined) %},hwaddr={{ netif_hwaddr }}{% endif %},ip={{ netif_ip4 }}/{{ netif_netmask }}{% if (netif_gw is defined) %},gw={{ netif_gw }}{% endif %}{% if (netif_ip6 is defined) %},ip6={{ netif_ip6 }}/{{ netif_netmask6 }}{% endif %}{% if (netif_ip6 is defined) and (netif_gw6 is defined) %},gw6={{ netif_gw6 }}{% endif %},{% if (netif_firewall is defined and netif_firewall) %}firewall=1{% endif %}"
        nameserver: "{{ nameserver }}"
        ostemplate: "local:vztmpl/{{ url_ostemplate | urlsplit('path') | basename }}"
        password: "{{ root_password }}"
        pubkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        onboot: "{{ onboot }}"

# Mirá el número de la VM
- name: Show the ID of the VM
  debug:
    var: container

# Extraer el número de VM
- name: Extract the ID of the VM from container var
  shell: pct list | grep -w "{{ proxmox_hostname }}" | cut -f 1 -d ' '
  delegate_to: "{{ api_host }}"
  register: VMID
  when: container is succeeded
  changed_when: false
  tags:
    - deploy

- debug:
    var: VMID
  tags:
    - deploy

# Arrancar el contenedor
- name: Turn on the container
  proxmox:
    node: "{{ node }}"
    api_user: "{{ api_user }}"
    api_host: "{{ api_host }}"
    api_password: "{{ node_deploy_password }}"
    vmid: "{{ VMID.stdout }}"
    state: started
  delegate_to: "{{ api_host }}"
  register: turned_on
  when: (container is not defined) or (container is succeeded)
  tags:
    - deploy

# Repintiendo ping cada 3s hasta que el el contenedor arranque
- name: Repeating ping every 3 seconds until the container starts
  wait_for_connection:
    delay: 3
    sleep: 3
    timeout: 30
  remote_user: root
  when: turned_on.changed
